/** 所有 localStorage key 名稱 — single source of truth */
export const STORAGE_KEYS = {
  TABS: 'purdex-tabs',
  HOSTS: 'purdex-hosts',
  SESSIONS: 'purdex-sessions',
  AGENT: 'purdex-agent',
  WORKSPACES: 'purdex-workspaces',
  HISTORY: 'purdex-history',
  I18N: 'purdex-i18n',
  THEMES: 'purdex-themes',
  UI_SETTINGS: 'purdex-ui-settings',
  GLOBAL_SETTINGS: 'purdex-global-settings',
  HOST_SETTINGS: 'purdex-host-settings',
  WORKSPACE_SETTINGS: 'purdex-workspace-settings',
  NOTIFICATION_SETTINGS: 'purdex-notification-settings',
  RESUME_TEMPLATES: 'purdex-resume-templates',
  BROWSER_HISTORY: 'purdex-browser-history',
  LAYOUT: 'purdex-layout',
  NEW_TAB_LAYOUT: 'purdex-newtab-layout',
  /** 手動管理（非 Zustand store），直接操作 localStorage，不走 browserStorage/syncManager */
  NOTIFICATION_SEEN: 'purdex-notification-seen',
  MODULE_CONFIG: 'purdex-module-config',
  MODULE_ENABLED: 'purdex-module-enabled',
  EDITOR_SETTINGS: 'purdex-editor-settings',
  QUICK_COMMANDS: 'purdex-quick-commands',
  SYNC_STATE: 'purdex-sync-state',
  PATH_CACHE_V1: 'purdex-path-cache-v1',
  RECENT_FILES: 'purdex-recent-files',
  PLACEHOLDER_FILES: 'purdex-placeholder-files',
} as const
